// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Contexts;

#nullable disable

namespace WebApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 9
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 10
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 9
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 10
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 11
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 12
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 13
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 14
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 15
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 11
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 12
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 13
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 14
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 15
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 16
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 17
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 18
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 19
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 20
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "customer",
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Featured"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Popular"
                        });
                });

            modelBuilder.Entity("WebApp.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("WebApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The EchoWave 2000 is a powerful vintage-style synthesizer with unique oscillators, customizable filters, and a built-in sequencer, arpeggiator, and modulation matrix.\n\nWhether you're a professional musician or a beginner, the EchoWave 2000 is the perfect tool for unleashing your creativity and exploring new sonic territories.",
                            Image = "product1.jpg",
                            Name = "EchoWave 2000",
                            Price = 899m
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Neptune Starlight is a compact yet powerful synthesizer that offers a wide range of sounds and features. With its advanced synthesis engine, intuitive interface, and onboard effects, you can easily create anything from classic analog tones to cutting-edge digital textures.\n\nWhether you're performing on stage or producing in the studio, the Neptune Starlight is an essential tool for any musician.",
                            Image = "product2.jpg",
                            Name = "Neptune Starlight",
                            Price = 499m
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Cosmic Voyager is a stunning analog synthesizer with a classic design that harkens back to the golden age of electronic music. Featuring a full-size keyboard, vintage-style filters, and a powerful modulation matrix, the Cosmic Voyager is a must-have for any synth enthusiast.\n\nWhether you're creating soaring lead lines, funky bass grooves, or complex soundscapes, the Cosmic Voyager has you covered.",
                            Image = "product3.jpg",
                            Name = "Cosmic Voyager",
                            Price = 1199m
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Nova Synth 2000 is a powerful virtual analog synthesizer that combines cutting-edge digital technology with classic analog sound. With its intuitive interface, advanced synthesis engine, and onboard effects, you can easily create anything from warm pads and strings to aggressive leads and basses.\n\nWhether you're a professional musician or a bedroom producer, the Nova Synth 2000 is the ultimate tool for sound design and music production.",
                            Image = "product4.jpg",
                            Name = "Nova Synth 2000",
                            Price = 699m
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Jupiter Station is a stunning digital synthesizer with a classic design that harkens back to the glory days of synth-pop. Featuring a massive sound engine, intuitive controls, and a sleek user interface, the Jupiter Station is the perfect tool for creating anything from lush pads and ambient textures to powerful leads and basses.\n\nWhether you're a professional musician or a hobbyist, the Jupiter Station is a must-have for any synth lover.",
                            Image = "product5.jpg",
                            Name = "Jupiter Station",
                            Price = 999m
                        },
                        new
                        {
                            Id = 6,
                            Description = "The Solaris Synth x2 is a cutting-edge digital synthesizer that combines advanced sound design capabilities with intuitive performance features. With its modular architecture, extensive modulation options, and powerful effects, the Solaris Synth x2 is the ultimate tool for creating complex and evolving soundscapes.\n\nWhether you're a sound designer, film composer, or electronic musician, the Solaris Synth x2 is the perfect choice for exploring new sonic frontiers.",
                            Image = "product6.jpg",
                            Name = "Solaris Synth x2",
                            Price = 1799m
                        },
                        new
                        {
                            Id = 7,
                            Description = "The Analog Dream 8 is a powerful analog synthesizer with a modern twist. Featuring classic oscillators, a versatile filter section, and a built-in sequencer, the Analog Dream 8 is the perfect tool for creating anything from fat bass lines to soaring leads.\n\nWhether you're a seasoned synth pro or a beginner, the Analog Dream 8 is an essential addition to your studio setup.",
                            Image = "product7.jpg",
                            Name = "Analog Dream 8",
                            Price = 799m
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Matrix Tribe is a groundbreaking digital synthesizer that offers unparalleled sound design capabilities. With its advanced modulation matrix, unique waveshaping algorithms, and built-in effects, the Matrix Tribe is the ultimate tool for creating complex and evolving textures.\n\nWhether you're a sound designer, experimental musician, or electronic artist, the Matrix Tribe is the perfect choice for pushing the boundaries of sound.",
                            Image = "product8.jpg",
                            Name = "Matrix Tribe",
                            Price = 1499m
                        },
                        new
                        {
                            Id = 9,
                            Description = "The MicroDoser XXL is a compact synthesizer that packs a punch. Featuring a powerful synthesis engine, a wide range of sounds, and an intuitive interface, the MicroDoser XXL is the perfect tool for creating anything from vintage-style analog tones to modern digital textures.\n\nWhether you're performing live or producing in the studio, the MicroDoser XXL is a versatile and essential tool for any musician.",
                            Image = "product9.jpg",
                            Name = "MicroDoser XXL",
                            Price = 599m
                        },
                        new
                        {
                            Id = 10,
                            Description = "The Solar Flax is a stunning digital synthesizer with a sleek and modern design. Featuring a powerful sound engine, intuitive controls, and a built-in arpeggiator, the Solar Flax is the perfect tool for creating anything from classic analog sounds to cutting-edge digital textures.\n\nWhether you're a professional musician or a hobbyist, the Solar Flax is a must-have for any synth lover.",
                            Image = "product10.jpg",
                            Name = "Solar Flax",
                            Price = 899m
                        },
                        new
                        {
                            Id = 11,
                            Description = "The Neon Pulse 5 is a legendary analog synthesizer that has been used on countless classic recordings. With its warm and rich sound, versatile filter section, and intuitive interface, the Neon Pulse 5 is still the standard by which all other synthesizers are judged.\n\nWhether you're a professional musician or a vintage synth collector, the Neon Pulse 5 is an essential addition to your studio setup.",
                            Image = "product11.jpg",
                            Name = "Neon Pulse 5",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 12,
                            Description = "The Velocity Drive is a powerful digital synthesizer that offers a wide range of sounds and features. With its advanced sound engine, intuitive interface, and onboard effects, you can easily create anything from classic analog tones to cutting-edge digital textures.\n\nWhether you're performing live or producing in the studio, the Velocity Drive is an essential tool for any musician.",
                            Image = "product12.jpg",
                            Name = "Velocity Drive",
                            Price = 499m
                        },
                        new
                        {
                            Id = 13,
                            Description = "The Modular Madness 88 is a customizable and expandable digital synthesizer that allows you to create your own unique sound. Featuring a modular design, you can add and remove modules to create a synth that is tailored to your specific needs.\n\nWith its advanced modulation capabilities, built-in effects, and intuitive interface, the Modular Madness 88 is the ultimate tool for sound design and experimentation.",
                            Image = "product13.jpg",
                            Name = "Modular Madness 88",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 14,
                            Description = "The Quantum Wave Z is a powerful and versatile digital synthesizer that offers a wide range of sounds and features. With its advanced sound engine, intuitive interface, and built-in effects, you can easily create anything from classic analog tones to modern digital textures.\n\nWhether you're performing live or producing in the studio, the Quantum Wave Z is an essential tool for any musician.",
                            Image = "product14.jpg",
                            Name = "Quantum Wave Z",
                            Price = 899m
                        },
                        new
                        {
                            Id = 15,
                            Description = "The InfinityX 888 is a modern analog synthesizer that builds upon the classic sound of the Prophet 5. Featuring a rich and warm sound, versatile filter section, and intuitive interface, the InfinityX 888 is the perfect tool for creating anything from fat bass lines to soaring leads.\n\nWhether you're a seasoned synth pro or a beginner, the InfinityX 888 is an essential addition to your studio setup.",
                            Image = "product15.jpg",
                            Name = "InfinityX 888",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 16,
                            Description = "The MicroQuantum 420 is a cutting-edge digital synthesizer that offers unparalleled sound design capabilities. Featuring advanced wavetable algorithms, a versatile filter section, and a built-in arpeggiator, the MicroQuantum 420 is the perfect tool for creating complex and evolving textures.\n\nWhether you're a sound designer, experimental musician, or electronic artist, the MicroQuantum 420 is the ultimate choice for pushing the boundaries of sound.",
                            Image = "product16.jpg",
                            Name = "MicroQuantum 420",
                            Price = 1299m
                        },
                        new
                        {
                            Id = 17,
                            Description = "The Moonbox Charger is a vintage analog synthesizer that has been used on countless classic recordings. With its warm and rich sound, versatile filter section, and intuitive interface, the Moonbox Charger is still a favorite among synth enthusiasts.\n\nWhether you're a vintage synth collector or a modern musician looking for classic tones, the Moonbox Charger is an essential addition to your studio setup.",
                            Image = "product17.jpg",
                            Name = "Moonbox Charger",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 18,
                            Description = "The ScreamR is a versatile digital synthesizer with a sleek and modern design. Featuring advanced sound synthesis algorithms, a wide range of sounds, and a built-in sequencer, the ScreamR is the perfect tool for creating anything from classic analog tones to cutting-edge digital textures.\n\nWhether you're a professional musician or a hobbyist, the ScreamR is a must-have for any synth lover.",
                            Image = "product18.jpg",
                            Name = "ScreamR",
                            Price = 999m
                        },
                        new
                        {
                            Id = 19,
                            Description = "The MiniMono Galactic is a powerful analog synthesizer with a classic sound. Featuring a versatile filter section, a built-in sequencer, and an intuitive interface, the MiniMono Galactic is perfect for creating everything from deep bass lines to soaring leads.\n\nWith its compact size and rugged construction, the MiniMono Galactic is perfect for both live performance and studio use.",
                            Image = "product19.jpg",
                            Name = "MiniMono Galactic",
                            Price = 599m
                        },
                        new
                        {
                            Id = 20,
                            Description = "The FM Galaxy Brain is a powerful digital synthesizer that uses frequency modulation to create complex and evolving sounds. Featuring advanced algorithms, a wide range of sounds, and a built-in effects section, the FM Galaxy Brain is the perfect tool for sound design and experimentation.\n\nWhether you're a synth enthusiast or a professional musician, the FM Galaxy Brain is an essential addition to your studio setup.",
                            Image = "product20.jpg",
                            Name = "FM Galaxy Brain",
                            Price = 1499m
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("WebApp.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
